version: '3'

services:
  api:
    build: api
    ports:
      - "3001:3001"
    networks: 
      - cuebiq-network
  client:
    build: web
    ports:
      - "80:80"
    networks: 
      - cuebiq-network
networks:
  cuebiq-network:
    driver: "bridge"